<?php

return [
    'standard' => 'craniumtek-graph-engineering-v1',
    'project' => 'PHOENIX',
    'adoption_level' => 1,
    'defaults' => [
        'max_retries' => 2,
        'require_correlation_id' => true,
        'require_evidence' => true,
        'deny_unbounded_machine_authority' => true,
        'deny_cross_project_database_writes' => true,
        'production_activation_authorized' => false,
    ],
    'graphs' => [
        'live_selling_operations_v1' => [
            'priority' => 'P0',
            'objective' => 'Coordinate a live-selling session from readiness through verified attribution and profitability without allowing AI to own canonical financial authority.',
            'start' => 'brand_store_input',
            'nodes' => [
                'brand_store_input' => ['type' => 'input'],
                'product_session_readiness' => ['type' => 'function', 'side_effect' => false],
                'host_creator_match' => ['type' => 'agent'],
                'content_script_plan' => ['type' => 'agent'],
                'media_traffic_plan' => ['type' => 'agent'],
                'campaign_policy_gate' => ['type' => 'policy_gate'],
                'session_approval' => ['type' => 'human_gate'],
                'live_session_record' => ['type' => 'function', 'side_effect' => true, 'idempotent' => true],
                'order_attribution_ingest' => ['type' => 'function', 'side_effect' => true, 'idempotent' => true],
                'finance_ledger_update' => ['type' => 'function', 'side_effect' => true, 'scope' => 'deterministic_ledger_only'],
                'profitability_verification' => ['type' => 'verification'],
                'optimization_reasoning' => ['type' => 'agent'],
                'session_terminal' => ['type' => 'terminal'],
            ],
            'edges' => [
                ['from' => 'brand_store_input', 'to' => 'product_session_readiness'],
                ['from' => 'product_session_readiness', 'to' => 'host_creator_match', 'when' => 'ready'],
                ['from' => 'host_creator_match', 'to' => 'content_script_plan'],
                ['from' => 'content_script_plan', 'to' => 'media_traffic_plan'],
                ['from' => 'media_traffic_plan', 'to' => 'campaign_policy_gate'],
                ['from' => 'campaign_policy_gate', 'to' => 'session_approval', 'when' => 'allowed'],
                ['from' => 'campaign_policy_gate', 'to' => 'session_terminal', 'when' => 'rejected_or_escalated'],
                ['from' => 'session_approval', 'to' => 'live_session_record', 'when' => 'approved'],
                ['from' => 'live_session_record', 'to' => 'order_attribution_ingest'],
                ['from' => 'order_attribution_ingest', 'to' => 'finance_ledger_update'],
                ['from' => 'finance_ledger_update', 'to' => 'profitability_verification'],
                ['from' => 'profitability_verification', 'to' => 'optimization_reasoning', 'when' => 'pass'],
                ['from' => 'optimization_reasoning', 'to' => 'session_terminal'],
            ],
        ],
        'foundation_modernization_v1' => [
            'priority' => 'P0',
            'objective' => 'Modernize the legacy scaffold into the approved Laravel/PostgreSQL DEV foundation without prematurely activating production.',
            'start' => 'source_of_truth',
            'nodes' => [
                'source_of_truth' => ['type' => 'state'],
                'legacy_inspection' => ['type' => 'function', 'side_effect' => false],
                'architecture_reasoning' => ['type' => 'agent'],
                'security_gate' => ['type' => 'policy_gate'],
                'dev_change' => ['type' => 'function', 'side_effect' => true, 'scope' => 'dev_only'],
                'test_verification' => ['type' => 'verification'],
                'environment_approval' => ['type' => 'human_gate'],
                'foundation_terminal' => ['type' => 'terminal'],
            ],
            'edges' => [
                ['from' => 'source_of_truth', 'to' => 'legacy_inspection'],
                ['from' => 'legacy_inspection', 'to' => 'architecture_reasoning'],
                ['from' => 'architecture_reasoning', 'to' => 'security_gate'],
                ['from' => 'security_gate', 'to' => 'dev_change', 'when' => 'allowed'],
                ['from' => 'dev_change', 'to' => 'test_verification'],
                ['from' => 'test_verification', 'to' => 'environment_approval', 'when' => 'pass'],
                ['from' => 'test_verification', 'to' => 'architecture_reasoning', 'when' => 'repair_required'],
                ['from' => 'environment_approval', 'to' => 'foundation_terminal'],
            ],
        ],
    ],
];
